# Generated by Django 3.0.4 on 2020-04-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('concentration', models.CharField(blank=True, max_length=200)),
                ('product_category', models.CharField(blank=True, choices=[('Sour', 'Sour'), ('Spicy', 'Spicy')], max_length=50)),
                ('product_type', models.CharField(blank=True, choices=[('THC', 'THC'), ('CBD', 'CBD')], max_length=50)),
                ('product_ingredients', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
