# Generated by Django 3.0.4 on 2020-05-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Frozen', 'Frozen')], default='Active', max_length=50),
        ),
    ]
