# Generated by Django 3.0.4 on 2020-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200504_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='default', max_length=16),
            preserve_default=False,
        ),
    ]
